version: 6.1.0.{build}
branches:
  only:
  - develop
configuration: release
image: Visual Studio 2022
platform: Any CPU
init:
- ps: >-
    Update-AppveyorBuild -Version "6.1.0.$env:appveyor_build_number-$(Get-Date -format yyyyMMdd)-$env:appveyor_repo_branch"

    Write-Host "6.1.0.$env:appveyor_build_number-$(Get-Date -format yyyyMMdd)-$env:appveyor_repo_branch"

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  assembly_version: 6.1.0.{build}
  file_version: 6.1.0.{build}
nuget:
  project_feed: true
before_build:
- cmd: dotnet restore ./src/EPPlus.sln
build:
  verbosity: minimal
test_script:
- dotnet test src\EPPlusTest\EPPlus.Test.csproj --configuration Release --no-build /property:Platform=AnyCPU
artifacts:
- path: '**\*.nupkg'
  name: EPPlus Nuget Package
